In [15]:
import skimage.measure
import numpy as np

A = np.arange(5*4).reshape(5, 4)
print(A)

B = skimage.measure.block_reduce(A, (2, 2), np.mean)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 2.5   4.5 ]
 [10.5  12.5 ]
 [ 8.25  9.25]]


In [1]:
from skimage.util.shape import view_as_windows
import numpy as np

A = np.arange(5*4).reshape(5, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [3]:
B = view_as_windows(A, (4,4),step=4)
print(B, B.shape)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]]] (1, 1, 4, 4)


In [7]:
C = view_as_windows(A, (2,2),step=2)
y=np.reshape(C, (-1, 2, 2))
print(y, y.shape)

[[[ 0  1]
  [ 4  5]]

 [[ 2  3]
  [ 6  7]]

 [[ 8  9]
  [12 13]]

 [[10 11]
  [14 15]]] (4, 2, 2)


In [8]:
y = np.expand_dims(y, axis=-1)
print(y, y.shape)

[[[[ 0]
   [ 1]]

  [[ 4]
   [ 5]]]


 [[[ 2]
   [ 3]]

  [[ 6]
   [ 7]]]


 [[[ 8]
   [ 9]]

  [[12]
   [13]]]


 [[[10]
   [11]]

  [[14]
   [15]]]] (4, 2, 2, 1)


In [9]:
mapR=C.shape[0]
mapC=C.shape[1]
B_=np.reshape(C, (mapR, mapC, y.shape[1], y.shape[2], y.shape[-1]))
print('B_.shape', B_.shape)

B_.shape (2, 2, 2, 2, 1)


In [14]:
B_1 = B_[:,:,:,:,0]
D=B_1.transpose(0,2,1,3).reshape(-1, B_1.shape[1]*B_1.shape[3])
print('D.shape', D.shape, D)

D.shape (4, 4) [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
